2024-12-23 20:56:43 INFO Running runs: []
2024-12-23 20:56:43 INFO Agent received command: run
2024-12-23 20:56:43 INFO Agent starting run with config:
	batch_size: 4
	learning_rate: 1.730254557356245e-05
	lora_alpha: 16
	lora_dropout: 0.1
	lora_r: 16
	max_samples: 1000
	num_epochs: 5
2024-12-23 20:56:43 INFO About to run command: /usr/bin/env python src/main.py --batch_size=4 --learning_rate=1.730254557356245e-05 --lora_alpha=16 --lora_dropout=0.1 --lora_r=16 --max_samples=1000 --num_epochs=5
2024-12-23 20:56:48 INFO Running runs: ['blhuphul']
2024-12-23 20:56:48 INFO Cleaning up finished run: blhuphul
2024-12-23 20:59:06 INFO Running runs: []
2024-12-23 20:59:07 INFO Agent received command: run
2024-12-23 20:59:07 INFO Agent starting run with config:
	batch_size: 4
	learning_rate: 1.3388746380002342e-05
	lora_alpha: 16
	lora_dropout: 0.1
	lora_r: 32
	max_samples: 1000
	num_epochs: 5
2024-12-23 20:59:07 INFO About to run command: /usr/bin/env python src/main.py --batch_size=4 --learning_rate=1.3388746380002342e-05 --lora_alpha=16 --lora_dropout=0.1 --lora_r=32 --max_samples=1000 --num_epochs=5
2024-12-23 20:59:12 INFO Running runs: ['r9yfpdy8']
2024-12-23 21:25:11 INFO Running runs: []
2024-12-23 21:25:11 INFO Agent received command: run
2024-12-23 21:25:11 INFO Agent starting run with config:
	batch_size: 8
	learning_rate: 0.00012949866252763995
	lora_alpha: 32
	lora_dropout: 0.1
	lora_r: 8
	max_samples: 1000
	num_epochs: 5
2024-12-23 21:25:11 INFO About to run command: /usr/bin/env python src/main.py --batch_size=8 --learning_rate=0.00012949866252763995 --lora_alpha=32 --lora_dropout=0.1 --lora_r=8 --max_samples=1000 --num_epochs=5
2024-12-23 21:25:16 INFO Running runs: ['nhe4p47m']
2024-12-23 21:47:44 INFO Cleaning up finished run: nhe4p47m
2024-12-23 21:52:59 INFO Running runs: []
2024-12-23 21:52:59 INFO Agent received command: run
2024-12-23 21:52:59 INFO Agent starting run with config:
	batch_size: 4
	learning_rate: 4.516404045197661e-05
	lora_alpha: 16
	lora_dropout: 0.1
	lora_r: 16
	max_samples: 1000
	num_epochs: 5
2024-12-23 21:52:59 INFO About to run command: /usr/bin/env python src/main.py --batch_size=4 --learning_rate=4.516404045197661e-05 --lora_alpha=16 --lora_dropout=0.1 --lora_r=16 --max_samples=1000 --num_epochs=5
2024-12-23 21:53:04 INFO Running runs: ['n2zd4nj2']
2024-12-23 21:53:04 INFO Cleaning up finished run: n2zd4nj2
2024-12-23 23:20:09 ERROR Error importing optional module sweeps
Traceback (most recent call last):
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/util.py", line 215, in import_module_lazy
    return sys.modules[name]
           ~~~~~~~~~~~^^^^^^
KeyError: 'sweeps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/util.py", line 244, in get_module
    return import_module_lazy(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/util.py", line 219, in import_module_lazy
    raise ModuleNotFoundError
ModuleNotFoundError
2024-12-23 23:20:09 ERROR Traceback (most recent call last):
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/cli/cli.py", line 869, in sweep
    tuner = wandb_controller()
            ^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/sdk/wandb_sweep.py", line 114, in controller
    from ..wandb_controller import _WandbController
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/wandb_controller.py", line 73, in <module>
    sweeps = get_module(
             ^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/util.py", line 251, in get_module
    raise wandb.Error(required)
wandb.errors.errors.Error: wandb[sweeps] is required to use the local controller. Please run `pip install wandb[sweeps]`.

2024-12-23 23:22:03 INFO Running runs: []
2024-12-23 23:25:46 INFO Running runs: []
2024-12-23 23:31:02 INFO Running runs: []
2024-12-23 23:37:33 ERROR 400 response executing GraphQL.
2024-12-23 23:37:33 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-12-23 23:37:33 ERROR Traceback (most recent call last):
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 1113, in sweep
    response = self.gql(
               ^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 365, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 393, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/cli/cli.py", line 1680, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/wandb_agent.py", line 531, in run_agent
    agent.run()
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/apis/internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/apis/normalize.py", line 35, in wrapper
    raise CommError(message, error)
wandb.errors.errors.CommError: name required for project query (Error 400: Bad Request)

2024-12-23 23:37:41 ERROR 400 response executing GraphQL.
2024-12-23 23:37:41 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-12-23 23:37:41 ERROR Traceback (most recent call last):
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 1113, in sweep
    response = self.gql(
               ^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 365, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 393, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/cli/cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/cli/cli.py", line 1680, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/wandb_agent.py", line 531, in run_agent
    agent.run()
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/apis/internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/s3nik/Desktop/nlp-project-3/midi_caption_project/venv/lib/python3.11/site-packages/wandb/apis/normalize.py", line 35, in wrapper
    raise CommError(message, error)
wandb.errors.errors.CommError: name required for project query (Error 400: Bad Request)

2024-12-23 23:38:50 INFO Running runs: []
2024-12-23 23:56:25 INFO Running runs: []
